version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - /Users/mkovacevic/Desktop/docker/kafka1:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    depends_on:
      - zookeeper


  kafka2:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9093:9093"
    volumes:
      - /Users/mkovacevic/Desktop/docker/kafka2:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    depends_on:
      - zookeeper


  tweet-producer:
    image: mkovacevic/tweet-producer-app:latest
    ports:
      - "8080:8080"
    tty: true
    environment:
      - KAFKA_SERVICE=kafka1:9092,kafka2:9093
      - FROM_DATE=201802010000
      - TO_DATE=201802282359
    depends_on:
      - zookeeper
      - kafka1
      - kafka2

volumes:
  zookeeper_data:
    driver: local

networks:
  default:
    #external: true
    name: twitter-streaming_default



