{
 "title": "Tweet collection dashboard",
 "time": { "from": "2014-12-31T23:00:00.000Z", "to": "2015-04-01T22:00:00.000Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tweet count per company",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval),\n  search_term,\n  count(id) AS \"tweet_count\"\nFROM tweets\nWHERE\n  $__timeFilter(created)\nGROUP BY 1, search_term\nORDER BY $__timeGroup(created,$__interval)"
    }
   ]
  },
  {
   "title": "Total tweets collected per company",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT search_term, count(*) as total\nFROM tweets\nGROUP BY search_term"
    }
   ]
  },
  {
   "title": "Tweet count",
   "type": "timeseries",
   "description": "Tweet count per day, shown for first 4 months during collection process.",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval),\n  count(id) AS \"tweet_count\"\nFROM tweets\nWHERE\n  $__timeFilter(created)\nGROUP BY 1\nORDER BY $__timeGroup(created,$__interval)"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Total tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets"
    }
   ]
  },
  {
   "title": "Tesla's tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets\nWHERE search_term = 'TSLA'"
    }
   ]
  },
  {
   "title": "Amazon's tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets\nWHERE search_term LIKE 'AMZN';"
    }
   ]
  },
  {
   "title": "Microsoft's tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets\nWHERE search_term = 'MSFT'"
    }
   ]
  },
  {
   "title": "Apple's tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets\nWHERE search_term = 'AAPL'"
    }
   ]
  },
  {
   "title": "Google's tweet collection progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM tweets\nWHERE search_term = 'GOOG'"
    }
   ]
  }
 ]
}